#%RAML 0.8
---
title: thisdayinmusic API
documentation:
    - title: thisdayinmusic REST API
      content: |
        Welcome to the thisdayinmusic API.
baseUri: http://{host}:{port}/{version}
version: v1
mediaType: application/json
protocols: [HTTP]

/events:
    displayName: Collection of events
    get:
        description: Get all event
    post:
        description: Create a new event
        body:
            application/json:
                schema: !include schemas/events.json

    /{id}:
        displayName: Collection-event
        get:
            description: Get a particular event
        delete:
            description: Delete a particular event
        patch:
            description: Update a particular event

/tracks:
    displayName: Collection of tracks
    get:
        description: Get all track
    post:
        description: Create a new track
        body:
            application/json:
                schema: !include schemas/tracks.json

    /{id}:
        displayName: Collection-track
        get:
            description: Get a particular track
        delete:
            description: Delete a particular track
        patch:
            description: Update a particular track

/playlists:
    displayName: Collection of playlists
    get:
        description: Get all playlist
    post:
        description: Create a new playlist
        body:
            application/json:
                schema: !include schemas/playlists.json

    /{id}:
        displayName: Collection-playlist
        get:
            description: Get a particular playlist
        delete:
            description: Delete a particular playlist
        patch:
            description: Update a particular playlist


/artists:
    displayName: Collection of artists
    get:
        description: Get all artist
    post:
        description: Create a new artist
        body:
            application/json:
                schema: !include schemas/artists.json

    /{id}:
        displayName: Collection-artist
        get:
            description: Get a particular artist
        delete:
            description: Delete a particular artist
        patch:
            description: Update a particular artist

